version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: artuser
      POSTGRES_PASSWORD: artpass
      POSTGRES_DB: artculture
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://artuser:artpass@db:5432/artculture?schema=public
      JWT_SECRET: myVeryStrongSecret123
    ports:
      - "3000:3000"
volumes:
  db_data:
